### ISSUE TITLE
Fournir la valeur de tehr de manière annuelle et non mensuelle

### ISSUE THREAD

**Issue by laem** [openfisca/openfisca-france#411]
See this [comment](https://github.com/openfisca/openfisca-france/pull/370#issuecomment-170543333) for the discussion.
The decompositions file that call TEHR need this line to be added to the formula, 

``` python
    calculate_output = calculate_output_divide
```

which doesn't seem to be the correct behaviour.

**Comment by cbenz** [comment]
Test is `nosetests openfisca_france/tests/test_decomposition_fiches_de_paie.py`

- fad86ba70657fb07b3d66c1d49ef76eacfd1c247 (on `master`, before `aide-embauche` branch) is OK
- 9bfb10fcbe2b5ae07e62c13ea78aab442e56f323 (on `aide-embauche` branch, without `calculate_output`) is ERROR
- 23dc1664b30e4244807997072bce52a61f951cd3 (on `aide-embauche` branch, with `calculate_output`) is OK

I run a `git bisect` and I come back :)

**Comment by cbenz** [comment]
The first commit to introduce the ERROR, and as a consequence the need for `calculate_output = calculate_output_divide`, is b7ba4693953eb2109c38ca1b352236baceea980b.

**Comment by benjello** [comment]
Once again, this problem of TEHR is related to the fact that the TEHR is paid only once a year (and the date is partly left up to the entreprise). So the the use of calculate_output_divide is OK until we choose a default date or a configurable date for the paiement of TEHR. We need to think about what is the best 
choice. So let leave this open for now. It is a minor issue.

**Comment by cbenz** [comment]
@benjello I certainly understand that, but my challenge here is to understand why a "period mismatch" error occurs at commit b7ba469 taking into account that `tehr` is never modified, nor the test.

**Comment by benjello** [comment]
trace is your friend then

**Comment by cbenz** [comment]
@laem Notice that in the last good commit 8ebbc2e9906688829d3b18c67ea422c1e1ecceb1 before the error comes, the first node of the decomposition is [`salaire_super_brut`](https://github.com/openfisca/openfisca-france/blob/8ebbc2e9906688829d3b18c67ea422c1e1ecceb1/openfisca_france/decompositions/fiche_de_paie_decomposition.xml#L5), which [calls `tehr`](https://github.com/openfisca/openfisca-france/blob/8ebbc2e9906688829d3b18c67ea422c1e1ecceb1/openfisca_france/model/revenus/activite/salarie.py#L730) with a `calculate_divide`.

I think that after that commit, since b7ba469, `tehr` is called directly by the decomposition which uses [`calculate_output`](https://github.com/openfisca/openfisca-core/blob/708bdd784032fda5433a312dd2727956f2878075/openfisca_core/decompositions.py#L25), which is "opt-in". And `salaire_super_brut` decomposition node does not exist anymore.

I hope that it's more clear.

**Comment by cbenz** [comment]
@laem I used the trace log in text version to find the solution. Using the web trace tool would have been more difficult since I would have needed to deploy a branch in development on the trace tool web server.

I created https://github.com/openfisca/openfisca-gitbook/issues/7 to document it

**Comment by cbenz** [comment]
Oops I thought this issue was only to explain why `tehr` needed `calculate_output`.
But it's more about modelizing it correctly, no?

@laem Close it if you want.

**Comment by laem** [comment]
Yes it is about rewriting it

**Comment by benjello** [comment]
@laem : is there stuff left to be done in here ?

**Comment by laem** [comment]
Yes ! This tax does not exist anymore (from the salaries of 2015) !

Apart from that, the problem was that this tax is paid yearly in the real world, but the current implementation lets us get a yearly_amount/12 value for each month. 

Which is wrong : the tax should trigger at a yearly salary of 1 million €, but wouldn't in the implementation on a salary 1 million < s < 12 million.

**But**, the usage is real : you might want to have an estimated monthly value (e.g. for a company, to put aside ~/12 of the tax each month), so we need to compute it like the `allegement fillon` which is also based on the yearly salaries. 

**Also**, as far as I know, the new way to pay all the `cotisations sociales`, the DSN, asks for a `calcul progressif`, which has an impact on all the cotisations `plafonnées` and has to be implemented in OpenFisca by default for all the `cotisations sociales`.

**Comment by MattiSG** [comment]
Ce problème a a priori été résolu indirectement via #685, qui force l'explicitation des périodes de calcul.
