### ISSUE TITLE
dependance branch fails tests

### ISSUE THREAD

**Issue by benjello** [openfisca/openfisca-france#582]
@cbenz could you tell me why the dependance branch which is only slightly different from the baremes-ipp branch [fails so many tests](https://travis-ci.org/openfisca/openfisca-france/builds/167414171) ?

Thanks

**Comment by cbenz** [comment]
@benjello The data validators are not aware of the `origin` attributes. This is because of the branch names and Travis behavior relying on [this script](https://github.com/openfisca/openfisca-france/blob/master/travis-change-other-repos-branches.sh)

I pushed a commit in `dependance` branch: c9166ac290ba183ebaa89faa32e1226242ac50fa

Let's see Travis results, for now it has not started.

**Comment by benjello** [comment]
@cbenz : you rock.
@elsaperdrix : we should fix the test on the PR !
