### ISSUE TITLE
Deployment of some test

### ISSUE THREAD

**Issue by benjello** [openfisca/openfisca-france#622]
OpenFisca-matplotlib [needs some tests that are not available](https://travis-ci.org/openfisca/openfisca-matplotlib/builds/179841641).
Should I add their path in [MANIFEST.in](https://github.com/openfisca/openfisca-france/blob/master/MANIFEST.in) ?

**Comment by benjello** [comment]
I need to fix this ASAP. Suggestions welcome ;-)

**Comment by benjello** [comment]
@fpagnoux  (since  @cbenz is absent) : could I update the MANISFEST.in to include the aforementioned test ? Or should I move the test to the openfisca/reform directory ?

**Comment by benjello** [comment]
@cbenz : could you please take a look at this please ?

**Comment by cbenz** [comment]
Indeed unit tests are not packaged (here in OpenFisca-France) since they are not intended to be run by the user who installs the package.
@MattiSG Is it the right thing to do from your point of view?

At first glance I ask myself why OpenFisca-Matplotlib should run a test coming from OpenFisca-France.
The answer is to access [this `Variable`](https://github.com/openfisca/openfisca-france/blob/f97c70fb304df9d86e2a86a6298da774abf79ea7/openfisca_france/tests/reforms/test_parametric_reform.py#L14-L28)

I think the more simple is to duplicate the sample reform in OpenFisca-Matplotlib, rather than packaging the test in OpenFisca-France.

**Comment by benjello** [comment]
@cbenz : thanks !

**Comment by MattiSG** [comment]
I can't be 100% affirmative since I have no specific experience with Python packaging.

However, from a general packaging experience, I would indeed think that tests should not be packaged as they are of no use to the consumer.

That reform should first be assessed. Why is it there? What does it provide? Is it just a symptom of bad architecture that should be changed? If not, then it should probably be bundled as part of a series of helpers that allow for dynamic modification of the legislation, and not as a bonus of running tests.
