### ISSUE TITLE
Add a sans objet level for contrat_de_travail

### ISSUE THREAD

**Issue by benjello** [openfisca/openfisca-france#661]
It would be useful for:
 - clarity/completeness: why somebody who is not working do have contrat-de-travail by default to temps plein (the actual default is the 0 value)
 - ease the survey data scenario

**Comment by benjello** [comment]
Kept open to change the level number sans_objet to 0 instead of 6

**Comment by MattiSG** [comment]
This was fixed in #662. In order to ease issues readability, if changing the `sans_objet` value to 0 instead of 6 is important for you, please open a new issue on this topic, also stating the reason why this has to be changed — maybe the community will come up with an alternative! :slightly_smiling_face:
